version: 2.1
orbs:
  ruby: circleci/ruby@1.4.0
  heroku: circleci/heroku@2.0

jobs:
  build:
    working_directory: ~/cc_fe # THIS SHOULD BE NAME OF YOUR APP
    docker:
      - image: cimg/ruby:3.1.1
        environment:
          PGHOST: localhost
          PGUSER: cc_fe # THIS SHOULD BE NAME OF YOUR APP
          RAILS_ENV: test
          CC_API_URL: https://frozen-savannah-58383.herokuapp.com
      - image: postgres:13.2
        environment:
          POSTGRES_USER: cc_fe # THIS SHOULD BE NAME OF YOUR APP
          POSTGRES_DB: cc_fe_test # find db name in /config/database.yml
          POSTGRES_PASSWORD:
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: cc_fe # THIS SHOULD BE NAME OF YOUR APP
          command: bundle -v
      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: calm-bastion-20348 # REPLACE WITH THE NAME OF YOUR HEROKU APP

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main # REPLACE "main" WITH THE NAME OF YOUR DEPLOYMENT BRANCH IF DIFFERENT
